services:
  app:
    #image: studentsapp
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db


  db:
    image: postgres:15
    hostname: postgres
    restart: always
    ports:
      - "8081:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: frogs_db
    volumes:
      - ./db-init/:/docker-entrypoint-initdb.d/

  pgadmin:
    image: dpage/pgadmin4
    links:
    - db
    ports:
    - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.stu
      PGADMIN_DEFAULT_PASSWORD: 123456
